#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Exit immediately if a command exits with a non-zero status
set -e
set -u
set -o pipefail

# ==============================================================================
# Parse command-line options FIRST (so we can pass -j to dependencies)
# ==============================================================================
BUILD_TYPE="Release"
STATIC_FLAG="OFF"
PROFILE_FLAG="OFF"
PARALLEL_FLAG=""

while getopts 'cdspj' OPTION
do
    echo "c [BUILD] Option Selected: -$OPTION"
    case "$OPTION" in
        c)
            BUILD_TYPE="Release"
            STATIC_FLAG="OFF"
            PROFILE_FLAG="OFF"
            ;;
        d)
            BUILD_TYPE="Debug"
            STATIC_FLAG="OFF"
            PROFILE_FLAG="OFF"
            ;;
        s)
            BUILD_TYPE="Release"
            STATIC_FLAG="ON"
            PROFILE_FLAG="OFF"
            ;;        
        p)
            BUILD_TYPE="RelWithDebInfo" 
            STATIC_FLAG="OFF"
            PROFILE_FLAG="ON"
            ;;
        j)
            # Enable parallel compilation
            PARALLEL_FLAG="--parallel"
            ;;
        *)
            echo "Usage: $0 [-c (release) | -d (debug) | -s (static) | -p (profile) | -j (parallel)]"
            exit 1
            ;;
    esac
done

# ==============================================================================
# Bootstrap CMake if it is not installed (e.g., in the competition container)
# ==============================================================================
if ! command -v cmake &> /dev/null; then
    echo "c [BUILD] cmake not found! Bootstrapping portable CMake using python3..."
    BOOTSTRAP_DIR="$SCRIPT_DIR/build/bootstrap-cmake"
    mkdir -p "$BOOTSTRAP_DIR"

    python3 -c "
import urllib.request
import os
import tarfile

version = '3.28.3'
tar_name = f'cmake-{version}-linux-x86_64.tar.gz'
url = f'https://github.com/Kitware/CMake/releases/download/v{version}/{tar_name}'

dest_tar = os.path.join('$BOOTSTRAP_DIR', tar_name)
print(f'Downloading portable CMake from {url}...')
try:
    urllib.request.urlretrieve(url, dest_tar)
    print('Extracting CMake...')
    with tarfile.open(dest_tar, 'r:gz') as tar:
        tar.extractall(path='$BOOTSTRAP_DIR')
    os.remove(dest_tar)
    print('CMake bootstrap completed.')
except Exception as e:
    print(f'Failed to bootstrap CMake: {e}')
    exit(1)
"

    # Add the extracted cmake binary to PATH
    export PATH="$BOOTSTRAP_DIR/cmake-3.28.3-linux-x86_64/bin:$PATH"
fi

# ==============================================================================
# Setup FetchContent overrides for offline competition builds if sources exist
# ==============================================================================
if [ -d "$SCRIPT_DIR/../../3rdParty/optree-src" ] && [ -d "$SCRIPT_DIR/../../3rdParty/bipe-src" ]; then
    echo "c [BUILD] Local 3rdParty source directories found. Setting up FetchContent overrides..."
    OPTREE_SRC_DIR=$(cd "$SCRIPT_DIR/../../3rdParty/optree-src" && pwd)
    BIPE_SRC_DIR=$(cd "$SCRIPT_DIR/../../3rdParty/bipe-src" && pwd)

    mkdir -p "$SCRIPT_DIR/build"
    cat <<EOF > "$SCRIPT_DIR/build/fc_toolchain.cmake"
# Auto-generated by build.sh to override FetchContent for offline competition builds
set(FETCHCONTENT_SOURCE_DIR_OPTREE "$OPTREE_SRC_DIR" CACHE PATH "Use local optree source" FORCE)
set(FETCHCONTENT_SOURCE_DIR_BIPE "$BIPE_SRC_DIR" CACHE PATH "Use local bipe source" FORCE)
set(OPTREE_BUILD_TESTS OFF CACHE BOOL "Disable optree tests" FORCE)
EOF
    export CMAKE_TOOLCHAIN_FILE="$SCRIPT_DIR/build/fc_toolchain.cmake"
else
    echo "c [BUILD] Local 3rdParty source directories not found. Dynamic downloads will be used."
fi

# ==============================================================================
# Check and build dependencies (d4)
# ==============================================================================
if [ "${D4_ALREADY_BUILT:-0}" -ne 1 ]; then
    D4_ROOT_DIR="$SCRIPT_DIR/../../"
    echo "c [BUILD] Parent library d4 is missing! Building d4 first..."

    CURRENT_DIR="$PWD"
    cd "$D4_ROOT_DIR"

    export GITLAB_TOKEN_LOGICAL="${GITLAB_TOKEN_LOGICAL:-glpat-eHavaAslBimi87EABf6MIW86MQp1OjJpdgk.01.0z0dxf0ko}"

    # Pass ALL arguments (e.g., -s -j) down to the parent script
    ./build.sh "$@"

    cd "$CURRENT_DIR"
    echo "c [BUILD] d4 built successfully."
else
    echo "c [BUILD] Skipping parent library build (already built)."
fi

# ==============================================================================
# Configure and build 'competition'
# ==============================================================================

# Create and enter the build directory
mkdir -p "$SCRIPT_DIR/build"
cd "$SCRIPT_DIR/build"

echo "c [BUILD] Configuring CMake (Type: $BUILD_TYPE, Static: $STATIC_FLAG, Profile: $PROFILE_FLAG)..."

cmake .. \
    -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
    -DBUILD_STATIC="$STATIC_FLAG" \
    -DBUILD_PROFILE="$PROFILE_FLAG"

echo "c [BUILD] Compiling executable using Make..."

# Unquoted $PARALLEL_FLAG so it expands to nothing if empty, or --parallel if set
cmake --build . $PARALLEL_FLAG

echo "c [BUILD] Build complete! The 'd4' competition executable is ready."
