#pragma once

// THIS FILE IS GENERATED BY gen_providers.py. DO NOT EDIT MANUALLY.

#include <nlohmann/json.hpp>
#include <string>
#include <map>
#include <vector>

#include "src/configurations/Configuration.hpp"
#include "src/configurations/ConfigurationBranchingHeuristic.hpp"
#include "src/configurations/ConfigurationCache.hpp"
#include "src/configurations/ConfigurationDpllStyleMethod.hpp"
#include "src/configurations/ConfigurationEREMethod.hpp"
#include "src/configurations/ConfigurationFormulaManager.hpp"
#include "src/configurations/ConfigurationMaxSharpSatMethod.hpp"
#include "src/configurations/ConfigurationMaxTMethod.hpp"
#include "src/configurations/ConfigurationMinSharpSatMethod.hpp"
#include "src/configurations/ConfigurationPartialOrderHeuristic.hpp"
#include "src/configurations/ConfigurationProjMcMethod.hpp"
#include "src/configurations/ConfigurationQbfCounter.hpp"
#include "src/configurations/ConfigurationSolver.hpp"
#include "src/options/branchingHeuristic/OptionBranchingHeuristic.hpp"
#include "src/options/branchingHeuristic/OptionPartialOrderHeuristic.hpp"
#include "src/options/cache/OptionBucketManager.hpp"
#include "src/options/cache/OptionCacheCleaningManager.hpp"
#include "src/options/cache/OptionCacheManager.hpp"
#include "src/options/formulaManager/OptionFormulaManager.hpp"
#include "src/options/methods/OptionDpllStyleMethod.hpp"
#include "src/options/methods/OptionEREMethod.hpp"
#include "src/options/methods/OptionMaxSharpSatMethod.hpp"
#include "src/options/methods/OptionMaxTMethod.hpp"
#include "src/options/methods/OptionMethodManager.hpp"
#include "src/options/methods/OptionMinSharpSatMethod.hpp"
#include "src/options/methods/OptionOperationManager.hpp"
#include "src/options/methods/OptionProjMcMethod.hpp"
#include "src/options/methods/OptionQbfCounter.hpp"
#include "src/options/solvers/OptionSolver.hpp"

namespace d4 {

    /**
     * @brief Trait to provide metadata about enums.
     */
    template<typename EnumType>
    struct EnumMetadata {
        static std::map<int, std::string> mapping() { return {}; }
        static std::string name() { return "UnknownEnum"; }
    };

    /**
     * @brief Helper to generate a documentation string for an enum.
     */
    template<typename EnumType>
    inline std::string get_enum_doc() {
        auto m = EnumMetadata<EnumType>::mapping();
        std::string doc = "";
        for (auto const& [val, label] : m) {
            if (!doc.empty()) doc += ", ";
            doc += std::to_string(val) + "=" + label;
        }
        return doc;
    }

    // Specializations – auto-generated from C++ enum definitions

    template<> struct EnumMetadata<BranchingHeuristicType> {
        static std::string name() { return "BranchingHeuristicType"; }
        static std::map<int, std::string> mapping() {
            return {{(int)BRANCHING_CLASSIC, "BRANCHING_CLASSIC"}, {(int)BRANCHING_LARGE_ARITY, "BRANCHING_LARGE_ARITY"}, {(int)BRANCHING_HYBRID_PARTIAL_CLASSIC, "BRANCHING_HYBRID_PARTIAL_CLASSIC"}};
        }
    };

    template<> struct EnumMetadata<CacheCleaningStrategy> {
        static std::string name() { return "CacheCleaningStrategy"; }
        static std::map<int, std::string> mapping() {
            return {{(int)CACHE_EXPECTATION, "CACHE_EXPECTATION"}, {(int)CACHE_NONE, "CACHE_NONE"}};
        }
    };

    template<> struct EnumMetadata<CachingMethod> {
        static std::string name() { return "CachingMethod"; }
        static std::map<int, std::string> mapping() {
            return {{(int)CACHE_NO_COL, "CACHE_NO_COL"}, {(int)CACHE_LIST, "CACHE_LIST"}};
        }
    };

    template<> struct EnumMetadata<ClauseRepresentation> {
        static std::string name() { return "ClauseRepresentation"; }
        static std::map<int, std::string> mapping() {
            return {{(int)CACHE_CLAUSE, "CACHE_CLAUSE"}, {(int)CACHE_INDEX, "CACHE_INDEX"}, {(int)CACHE_SYM, "CACHE_SYM"}, {(int)CACHE_COMBI, "CACHE_COMBI"}};
        }
    };

    template<> struct EnumMetadata<ModeStore> {
        static std::string name() { return "ModeStore"; }
        static std::map<int, std::string> mapping() {
            return {{(int)CACHE_ALL, "CACHE_ALL"}, {(int)CACHE_NB, "CACHE_NB"}, {(int)CACHE_NT, "CACHE_NT"}};
        }
    };

    template<> struct EnumMetadata<OperationType> {
        static std::string name() { return "OperationType"; }
        static std::map<int, std::string> mapping() {
            return {{(int)OP_COUNTING, "OP_COUNTING"}, {(int)OP_CIRC, "OP_CIRC"}};
        }
    };

    template<> struct EnumMetadata<PhaseHeuristicType> {
        static std::string name() { return "PhaseHeuristicType"; }
        static std::map<int, std::string> mapping() {
            return {{(int)PHASE_FALSE, "PHASE_FALSE"}, {(int)PHASE_TRUE, "PHASE_TRUE"}, {(int)PHASE_POLARITY, "PHASE_POLARITY"}, {(int)PHASE_OCCURRENCE, "PHASE_OCCURRENCE"}};
        }
    };

    template<> struct EnumMetadata<ScoringMethodType> {
        static std::string name() { return "ScoringMethodType"; }
        static std::map<int, std::string> mapping() {
            return {{(int)SCORE_MOM, "SCORE_MOM"}, {(int)SCORE_DLCS, "SCORE_DLCS"}, {(int)SCORE_VSIDS, "SCORE_VSIDS"}, {(int)SCORE_VSADS, "SCORE_VSADS"}, {(int)SCORE_JWTS, "SCORE_JWTS"}};
        }
    };

    template<> struct EnumMetadata<SolverName> {
        static std::string name() { return "SolverName"; }
        static std::map<int, std::string> mapping() {
            return {{(int)GLUCOSE_CNF, "GLUCOSE_CNF"}, {(int)MINISAT_CNF, "MINISAT_CNF"}};
        }
    };

    template<> struct EnumMetadata<SpecUpdateType> {
        static std::string name() { return "SpecUpdateType"; }
        static std::map<int, std::string> mapping() {
            return {{(int)SPEC_DYNAMIC, "SPEC_DYNAMIC"}, {(int)SPEC_DYNAMIC_BLOCKED_SIMP, "SPEC_DYNAMIC_BLOCKED_SIMP"}, {(int)SPEC_DYNAMIC_PURE_SIMP, "SPEC_DYNAMIC_PURE_SIMP"}};
        }
    };

} // namespace d4
