/**
 * eliminator
 *  Copyright (C) 2021  Lagniez Jean-Marie
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#pragma once

#include <vector>

#include "src/utils/ProblemTypes.hpp"
#include "src/utils/Timer.hpp"
namespace bipe {
namespace eliminator {

/**
 * @brief Applies Bounded Variable Elimination (BVE) via resolution.
 *
 * This class attempts to simplify a CNF formula by resolving away specific
 * non-input (internal/output) variables, provided that doing so does not
 * exceed a specified clause limit.
 */
class EliminatorResolution {
 private:
  std::vector<bool> m_marked;
  std::vector<bool> m_isUnit;
  unsigned m_largerClauses;

  /**
   * @brief Selects and extracts a candidate variable for elimination.
   *
   * @param vars The set of candidate variables available for elimination.
   * @param occClauses The adjacency list mapping each variable/literal to its
   * clauses.
   * @return A variable selected from `vars`, or `var_Undef` if the list is
   * empty.
   */
  Var selectVarAndPop(std::vector<Var>& vars,
                      std::vector<std::vector<unsigned>>& occClauses);

  /**
   * @brief Performs all pairwise resolutions to eliminate a given variable.
   *
   * @param v The variable targeted for elimination.
   * @param clauses The current set of clauses in the formula.
   * @param occClauses The occurrence list mapping variables to their respective
   * clauses.
   * @param[out] result The new set of clauses generated by resolving on
   * variable `v`.
   * @return True if the resolution process completes successfully (e.g.,
   * without exceeding size limits), false otherwise.
   */
  bool generateAllResolution(Var v, std::vector<std::vector<Lit>>& clauses,
                             std::vector<std::vector<unsigned>>& occClauses,
                             std::vector<std::vector<Lit>>& result);

  /**
   * @brief Removes a specific clause index from an occurrence list.
   *
   * Performs a fast removal by swapping the target element with the last
   * element in the vector and popping it.
   *
   * @param occ The occurrence list for a specific literal or variable.
   * @param idx The index of the clause to remove from the list.
   */
  inline void removeOcc(std::vector<unsigned>& occ, unsigned idx) {
    unsigned pos = 0;
    while (pos < occ.size() && occ[pos] != idx) pos++;
    assert(pos < occ.size());
    occ[pos] = occ.back();
    occ.pop_back();
  }

 public:
  /**
   * @brief Attempts to eliminate non-input variables from the formula.
   *
   * @param nbVar The total number of variables in the input formula.
   * @param[in,out] clauses The CNF formula to be processed and modified
   * in-place.
   * @param input The set of protected input variables that must NOT be
   * eliminated.
   * @param[out] eliminated A list to store the literals/variables that were
   * successfully eliminated.
   * @param verbose If true, prints detailed progress information to the
   * standard output.
   * @param limitNbClauses The maximum allowed number of clauses (or maximum
   * growth limit) permitted during the resolution steps.
   * @param timer The timer used to strictly enforce execution time limits.
   */
  void eliminate(unsigned nbVar, std::vector<std::vector<Lit>>& clauses,
                 std::vector<Var>& input, std::vector<Lit>& eliminated,
                 bool verbose, unsigned limitNbClauses, const Timer& timer);
};

}  // namespace eliminator
}  // namespace bipe